### ISSUE TITLE
DB insert into records not working

### ISSUE THREAD

**Issue by snunezcr** [SPEC-collab/CSSSA2022#3]
From transcript

```
Traceback (most recent call last):
  File "/Users/snunez/Research/CSSSA2022/main.py", line 59, in <module>
    main()
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/snunez/Research/CSSSA2022/main.py", line 46, in main
    md.run_model(
  File "/Users/snunez/Research/CSSSA2022/csssa2022/modeldriver.py", line 59, in run_model
    model.run()
  File "/Users/snunez/Research/CSSSA2022/csssa2022/abstractvotermodel.py", line 91, in run
    self.save_all()
  File "/Users/snunez/Research/CSSSA2022/csssa2022/abstractvotermodel.py", line 83, in save_all
    self.save(i)
  File "/Users/snunez/Research/CSSSA2022/csssa2022/abstractvotermodel.py", line 75, in save
    self.db.insert_record(self.agent_to_record(i))
  File "/Users/snunez/Research/CSSSA2022/csssa2022/database.py", line 61, in insert_record
    self.cur.execute('insert into records values (?, ?, ?, ?, ?, ?)',
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

**Comment by nunezco2** [comment]
Solved by converting uuid1 into String.
